### PR TITLE
Var Changes

### PR DESCRIPTION
**Pull request by Linuturk**
Also fixes the improperly formatted md5sum file.

### CODE REVIEW

**Comment by Linuturk** [comment]
Tests will fail because the master branch has an incorrectly formatted md5sum file. This PR fixes it.

**Comment by rackerroush** [comment]
Circle is still throwing an error.

**Comment by Linuturk** [comment]
Yeah, because the scripts hit master instead of this testing branch. Here's my local test:
```
root@dd937e866bf1:~# git clone https://github.com/rax-brazil/pub-ssh-keys.git
Cloning into 'pub-ssh-keys'...
remote: Counting objects: 157, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 157 (delta 2), reused 0 (delta 0), pack-reused 149
Receiving objects: 100% (157/157), 20.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (73/73), done.
Checking connectivity... done.
root@dd937e866bf1:~# cd pub-ssh-keys/
root@dd937e866bf1:~/pub-ssh-keys# git checkout varchanges
Branch varchanges set up to track remote branch varchanges from origin.
Switched to a new branch 'varchanges'
root@dd937e866bf1:~/pub-ssh-keys# git pull
Already up-to-date.
root@dd937e866bf1:~/pub-ssh-keys# bash rackerkeys.sh 
Adding the Rackspace Management User...Done
Checking file checksum...authorized_keys: OK
Correcting SSH configuration permissions...Done
Adding crontab entry for continued updates...Done
Configuring sudo for Rackspace Management User...Done
root@dd937e866bf1:~/pub-ssh-keys# bash rackerkeys.sh 
Rackspace Management User already exists...Skipping
Checking file checksum...authorized_keys: OK
Correcting SSH configuration permissions...Done
Crontab already configured for updates...Skipping
Sudo already configured for Rackspace Management User...Skipping
root@dd937e866bf1:~/pub-ssh-keys#
```

**Comment by rackerroush** [comment]
What is the point of having it test the master branch if we want it to be a form of validation for merging it into master?

**Comment by Linuturk** [comment]
In a perfect world, our script would test against the current branch. I can modify the script to do that no problem. I'll work on that now.

The reason it is testing against master is because we want master to work and we want to prevent any breaking changes from hitting the master branch and rolling out to the nodes running the script.

**Pull request merged**
