### PR TITLE
fixed keys

### PR DESCRIPTION
**Pull request by mattbradyr**

### CODE REVIEW

**Comment by horacio3** [comment]
You are already there
https://github.com/rax-brazil/pub-ssh-keys/pull/100
https://github.com/rax-brazil/pub-ssh-keys/blob/master/authorized_keys#L97-L98

**Comment by horacio3** [comment]
Are you switching out your keys?

**Comment by mattbradyr** [comment]
yes

**Comment by horacio3** [comment]
You need to rebase from master as Will B has been added since your pull and then get new authorized keys.Squash the commits as well.

**Comment by horacio3** [comment]
Canceling as we completed here https://github.com/rax-brazil/pub-ssh-keys/pull/102

**Pull request closed without merging**
